//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PubsEntities : DbContext
    {
        public PubsEntities()
            : base("name=PubsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<authors> authors { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<jobs> jobs { get; set; }
        public DbSet<pub_info> pub_info { get; set; }
        public DbSet<publishers> publishers { get; set; }
        public DbSet<sales> sales { get; set; }
        public DbSet<stores> stores { get; set; }
        public DbSet<titleauthor> titleauthor { get; set; }
        public DbSet<titles> titles { get; set; }
        public DbSet<discounts> discounts { get; set; }
        public DbSet<roysched> roysched { get; set; }
    }
}
