//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class stores
    {
        public stores()
        {
            this.sales = new HashSet<sales>();
            this.discounts = new HashSet<discounts>();
        }
    
        public string stor_id { get; set; }
        public string stor_name { get; set; }
        public string stor_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
    
        public virtual ICollection<sales> sales { get; set; }
        public virtual ICollection<discounts> discounts { get; set; }
    }
}
